with-expecter: true
dir: 'mocks'
outpkg: 'mocks'

packages:
  github.com/arangodb/go-driver/v2/arangodb:
    interfaces:
      Client:
        config:
          filename: arangodb_driver_client.go
      Database:
        config:
          filename: arangodb_driver_database.go