// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	arangodb "github.com/arangodb/go-driver/v2/arangodb"

	mock "github.com/stretchr/testify/mock"
)

// MockDatabase is an autogenerated mock type for the Database type
type MockDatabase struct {
	mock.Mock
}

type MockDatabase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDatabase) EXPECT() *MockDatabase_Expecter {
	return &MockDatabase_Expecter{mock: &_m.Mock}
}

// Analyzer provides a mock function with given fields: ctx, name
func (_m *MockDatabase) Analyzer(ctx context.Context, name string) (arangodb.Analyzer, error) {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for Analyzer")
	}

	var r0 arangodb.Analyzer
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (arangodb.Analyzer, error)); ok {
		return rf(ctx, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) arangodb.Analyzer); ok {
		r0 = rf(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(arangodb.Analyzer)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDatabase_Analyzer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Analyzer'
type MockDatabase_Analyzer_Call struct {
	*mock.Call
}

// Analyzer is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockDatabase_Expecter) Analyzer(ctx interface{}, name interface{}) *MockDatabase_Analyzer_Call {
	return &MockDatabase_Analyzer_Call{Call: _e.mock.On("Analyzer", ctx, name)}
}

func (_c *MockDatabase_Analyzer_Call) Run(run func(ctx context.Context, name string)) *MockDatabase_Analyzer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockDatabase_Analyzer_Call) Return(_a0 arangodb.Analyzer, _a1 error) *MockDatabase_Analyzer_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDatabase_Analyzer_Call) RunAndReturn(run func(context.Context, string) (arangodb.Analyzer, error)) *MockDatabase_Analyzer_Call {
	_c.Call.Return(run)
	return _c
}

// Analyzers provides a mock function with given fields: ctx
func (_m *MockDatabase) Analyzers(ctx context.Context) (arangodb.AnalyzersResponseReader, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Analyzers")
	}

	var r0 arangodb.AnalyzersResponseReader
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (arangodb.AnalyzersResponseReader, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) arangodb.AnalyzersResponseReader); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(arangodb.AnalyzersResponseReader)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDatabase_Analyzers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Analyzers'
type MockDatabase_Analyzers_Call struct {
	*mock.Call
}

// Analyzers is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockDatabase_Expecter) Analyzers(ctx interface{}) *MockDatabase_Analyzers_Call {
	return &MockDatabase_Analyzers_Call{Call: _e.mock.On("Analyzers", ctx)}
}

func (_c *MockDatabase_Analyzers_Call) Run(run func(ctx context.Context)) *MockDatabase_Analyzers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockDatabase_Analyzers_Call) Return(_a0 arangodb.AnalyzersResponseReader, _a1 error) *MockDatabase_Analyzers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDatabase_Analyzers_Call) RunAndReturn(run func(context.Context) (arangodb.AnalyzersResponseReader, error)) *MockDatabase_Analyzers_Call {
	_c.Call.Return(run)
	return _c
}

// BeginTransaction provides a mock function with given fields: ctx, cols, opts
func (_m *MockDatabase) BeginTransaction(ctx context.Context, cols arangodb.TransactionCollections, opts *arangodb.BeginTransactionOptions) (arangodb.Transaction, error) {
	ret := _m.Called(ctx, cols, opts)

	if len(ret) == 0 {
		panic("no return value specified for BeginTransaction")
	}

	var r0 arangodb.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, arangodb.TransactionCollections, *arangodb.BeginTransactionOptions) (arangodb.Transaction, error)); ok {
		return rf(ctx, cols, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, arangodb.TransactionCollections, *arangodb.BeginTransactionOptions) arangodb.Transaction); ok {
		r0 = rf(ctx, cols, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(arangodb.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, arangodb.TransactionCollections, *arangodb.BeginTransactionOptions) error); ok {
		r1 = rf(ctx, cols, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDatabase_BeginTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BeginTransaction'
type MockDatabase_BeginTransaction_Call struct {
	*mock.Call
}

// BeginTransaction is a helper method to define mock.On call
//   - ctx context.Context
//   - cols arangodb.TransactionCollections
//   - opts *arangodb.BeginTransactionOptions
func (_e *MockDatabase_Expecter) BeginTransaction(ctx interface{}, cols interface{}, opts interface{}) *MockDatabase_BeginTransaction_Call {
	return &MockDatabase_BeginTransaction_Call{Call: _e.mock.On("BeginTransaction", ctx, cols, opts)}
}

func (_c *MockDatabase_BeginTransaction_Call) Run(run func(ctx context.Context, cols arangodb.TransactionCollections, opts *arangodb.BeginTransactionOptions)) *MockDatabase_BeginTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(arangodb.TransactionCollections), args[2].(*arangodb.BeginTransactionOptions))
	})
	return _c
}

func (_c *MockDatabase_BeginTransaction_Call) Return(_a0 arangodb.Transaction, _a1 error) *MockDatabase_BeginTransaction_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDatabase_BeginTransaction_Call) RunAndReturn(run func(context.Context, arangodb.TransactionCollections, *arangodb.BeginTransactionOptions) (arangodb.Transaction, error)) *MockDatabase_BeginTransaction_Call {
	_c.Call.Return(run)
	return _c
}

// ClearQueryCache provides a mock function with given fields: ctx
func (_m *MockDatabase) ClearQueryCache(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ClearQueryCache")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockDatabase_ClearQueryCache_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClearQueryCache'
type MockDatabase_ClearQueryCache_Call struct {
	*mock.Call
}

// ClearQueryCache is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockDatabase_Expecter) ClearQueryCache(ctx interface{}) *MockDatabase_ClearQueryCache_Call {
	return &MockDatabase_ClearQueryCache_Call{Call: _e.mock.On("ClearQueryCache", ctx)}
}

func (_c *MockDatabase_ClearQueryCache_Call) Run(run func(ctx context.Context)) *MockDatabase_ClearQueryCache_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockDatabase_ClearQueryCache_Call) Return(_a0 error) *MockDatabase_ClearQueryCache_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDatabase_ClearQueryCache_Call) RunAndReturn(run func(context.Context) error) *MockDatabase_ClearQueryCache_Call {
	_c.Call.Return(run)
	return _c
}

// ClearQueryPlanCache provides a mock function with given fields: ctx
func (_m *MockDatabase) ClearQueryPlanCache(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ClearQueryPlanCache")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockDatabase_ClearQueryPlanCache_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClearQueryPlanCache'
type MockDatabase_ClearQueryPlanCache_Call struct {
	*mock.Call
}

// ClearQueryPlanCache is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockDatabase_Expecter) ClearQueryPlanCache(ctx interface{}) *MockDatabase_ClearQueryPlanCache_Call {
	return &MockDatabase_ClearQueryPlanCache_Call{Call: _e.mock.On("ClearQueryPlanCache", ctx)}
}

func (_c *MockDatabase_ClearQueryPlanCache_Call) Run(run func(ctx context.Context)) *MockDatabase_ClearQueryPlanCache_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockDatabase_ClearQueryPlanCache_Call) Return(_a0 error) *MockDatabase_ClearQueryPlanCache_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDatabase_ClearQueryPlanCache_Call) RunAndReturn(run func(context.Context) error) *MockDatabase_ClearQueryPlanCache_Call {
	_c.Call.Return(run)
	return _c
}

// ClearSlowAQLQueries provides a mock function with given fields: ctx, all
func (_m *MockDatabase) ClearSlowAQLQueries(ctx context.Context, all *bool) error {
	ret := _m.Called(ctx, all)

	if len(ret) == 0 {
		panic("no return value specified for ClearSlowAQLQueries")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *bool) error); ok {
		r0 = rf(ctx, all)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockDatabase_ClearSlowAQLQueries_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClearSlowAQLQueries'
type MockDatabase_ClearSlowAQLQueries_Call struct {
	*mock.Call
}

// ClearSlowAQLQueries is a helper method to define mock.On call
//   - ctx context.Context
//   - all *bool
func (_e *MockDatabase_Expecter) ClearSlowAQLQueries(ctx interface{}, all interface{}) *MockDatabase_ClearSlowAQLQueries_Call {
	return &MockDatabase_ClearSlowAQLQueries_Call{Call: _e.mock.On("ClearSlowAQLQueries", ctx, all)}
}

func (_c *MockDatabase_ClearSlowAQLQueries_Call) Run(run func(ctx context.Context, all *bool)) *MockDatabase_ClearSlowAQLQueries_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*bool))
	})
	return _c
}

func (_c *MockDatabase_ClearSlowAQLQueries_Call) Return(_a0 error) *MockDatabase_ClearSlowAQLQueries_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDatabase_ClearSlowAQLQueries_Call) RunAndReturn(run func(context.Context, *bool) error) *MockDatabase_ClearSlowAQLQueries_Call {
	_c.Call.Return(run)
	return _c
}

// CollectionExists provides a mock function with given fields: ctx, name
func (_m *MockDatabase) CollectionExists(ctx context.Context, name string) (bool, error) {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for CollectionExists")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(ctx, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, name)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDatabase_CollectionExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CollectionExists'
type MockDatabase_CollectionExists_Call struct {
	*mock.Call
}

// CollectionExists is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockDatabase_Expecter) CollectionExists(ctx interface{}, name interface{}) *MockDatabase_CollectionExists_Call {
	return &MockDatabase_CollectionExists_Call{Call: _e.mock.On("CollectionExists", ctx, name)}
}

func (_c *MockDatabase_CollectionExists_Call) Run(run func(ctx context.Context, name string)) *MockDatabase_CollectionExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockDatabase_CollectionExists_Call) Return(_a0 bool, _a1 error) *MockDatabase_CollectionExists_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDatabase_CollectionExists_Call) RunAndReturn(run func(context.Context, string) (bool, error)) *MockDatabase_CollectionExists_Call {
	_c.Call.Return(run)
	return _c
}

// Collections provides a mock function with given fields: ctx
func (_m *MockDatabase) Collections(ctx context.Context) ([]arangodb.Collection, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Collections")
	}

	var r0 []arangodb.Collection
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]arangodb.Collection, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []arangodb.Collection); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]arangodb.Collection)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDatabase_Collections_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Collections'
type MockDatabase_Collections_Call struct {
	*mock.Call
}

// Collections is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockDatabase_Expecter) Collections(ctx interface{}) *MockDatabase_Collections_Call {
	return &MockDatabase_Collections_Call{Call: _e.mock.On("Collections", ctx)}
}

func (_c *MockDatabase_Collections_Call) Run(run func(ctx context.Context)) *MockDatabase_Collections_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockDatabase_Collections_Call) Return(_a0 []arangodb.Collection, _a1 error) *MockDatabase_Collections_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDatabase_Collections_Call) RunAndReturn(run func(context.Context) ([]arangodb.Collection, error)) *MockDatabase_Collections_Call {
	_c.Call.Return(run)
	return _c
}

// CreateArangoSearchAliasView provides a mock function with given fields: ctx, name, options
func (_m *MockDatabase) CreateArangoSearchAliasView(ctx context.Context, name string, options *arangodb.ArangoSearchAliasViewProperties) (arangodb.ArangoSearchViewAlias, error) {
	ret := _m.Called(ctx, name, options)

	if len(ret) == 0 {
		panic("no return value specified for CreateArangoSearchAliasView")
	}

	var r0 arangodb.ArangoSearchViewAlias
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *arangodb.ArangoSearchAliasViewProperties) (arangodb.ArangoSearchViewAlias, error)); ok {
		return rf(ctx, name, options)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *arangodb.ArangoSearchAliasViewProperties) arangodb.ArangoSearchViewAlias); ok {
		r0 = rf(ctx, name, options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(arangodb.ArangoSearchViewAlias)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *arangodb.ArangoSearchAliasViewProperties) error); ok {
		r1 = rf(ctx, name, options)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDatabase_CreateArangoSearchAliasView_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateArangoSearchAliasView'
type MockDatabase_CreateArangoSearchAliasView_Call struct {
	*mock.Call
}

// CreateArangoSearchAliasView is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - options *arangodb.ArangoSearchAliasViewProperties
func (_e *MockDatabase_Expecter) CreateArangoSearchAliasView(ctx interface{}, name interface{}, options interface{}) *MockDatabase_CreateArangoSearchAliasView_Call {
	return &MockDatabase_CreateArangoSearchAliasView_Call{Call: _e.mock.On("CreateArangoSearchAliasView", ctx, name, options)}
}

func (_c *MockDatabase_CreateArangoSearchAliasView_Call) Run(run func(ctx context.Context, name string, options *arangodb.ArangoSearchAliasViewProperties)) *MockDatabase_CreateArangoSearchAliasView_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*arangodb.ArangoSearchAliasViewProperties))
	})
	return _c
}

func (_c *MockDatabase_CreateArangoSearchAliasView_Call) Return(_a0 arangodb.ArangoSearchViewAlias, _a1 error) *MockDatabase_CreateArangoSearchAliasView_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDatabase_CreateArangoSearchAliasView_Call) RunAndReturn(run func(context.Context, string, *arangodb.ArangoSearchAliasViewProperties) (arangodb.ArangoSearchViewAlias, error)) *MockDatabase_CreateArangoSearchAliasView_Call {
	_c.Call.Return(run)
	return _c
}

// CreateArangoSearchView provides a mock function with given fields: ctx, name, options
func (_m *MockDatabase) CreateArangoSearchView(ctx context.Context, name string, options *arangodb.ArangoSearchViewProperties) (arangodb.ArangoSearchView, error) {
	ret := _m.Called(ctx, name, options)

	if len(ret) == 0 {
		panic("no return value specified for CreateArangoSearchView")
	}

	var r0 arangodb.ArangoSearchView
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *arangodb.ArangoSearchViewProperties) (arangodb.ArangoSearchView, error)); ok {
		return rf(ctx, name, options)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *arangodb.ArangoSearchViewProperties) arangodb.ArangoSearchView); ok {
		r0 = rf(ctx, name, options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(arangodb.ArangoSearchView)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *arangodb.ArangoSearchViewProperties) error); ok {
		r1 = rf(ctx, name, options)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDatabase_CreateArangoSearchView_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateArangoSearchView'
type MockDatabase_CreateArangoSearchView_Call struct {
	*mock.Call
}

// CreateArangoSearchView is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - options *arangodb.ArangoSearchViewProperties
func (_e *MockDatabase_Expecter) CreateArangoSearchView(ctx interface{}, name interface{}, options interface{}) *MockDatabase_CreateArangoSearchView_Call {
	return &MockDatabase_CreateArangoSearchView_Call{Call: _e.mock.On("CreateArangoSearchView", ctx, name, options)}
}

func (_c *MockDatabase_CreateArangoSearchView_Call) Run(run func(ctx context.Context, name string, options *arangodb.ArangoSearchViewProperties)) *MockDatabase_CreateArangoSearchView_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*arangodb.ArangoSearchViewProperties))
	})
	return _c
}

func (_c *MockDatabase_CreateArangoSearchView_Call) Return(_a0 arangodb.ArangoSearchView, _a1 error) *MockDatabase_CreateArangoSearchView_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDatabase_CreateArangoSearchView_Call) RunAndReturn(run func(context.Context, string, *arangodb.ArangoSearchViewProperties) (arangodb.ArangoSearchView, error)) *MockDatabase_CreateArangoSearchView_Call {
	_c.Call.Return(run)
	return _c
}

// CreateCollectionV2 provides a mock function with given fields: ctx, name, props
func (_m *MockDatabase) CreateCollectionV2(ctx context.Context, name string, props *arangodb.CreateCollectionPropertiesV2) (arangodb.Collection, error) {
	ret := _m.Called(ctx, name, props)

	if len(ret) == 0 {
		panic("no return value specified for CreateCollectionV2")
	}

	var r0 arangodb.Collection
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *arangodb.CreateCollectionPropertiesV2) (arangodb.Collection, error)); ok {
		return rf(ctx, name, props)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *arangodb.CreateCollectionPropertiesV2) arangodb.Collection); ok {
		r0 = rf(ctx, name, props)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(arangodb.Collection)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *arangodb.CreateCollectionPropertiesV2) error); ok {
		r1 = rf(ctx, name, props)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDatabase_CreateCollectionV2_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateCollectionV2'
type MockDatabase_CreateCollectionV2_Call struct {
	*mock.Call
}

// CreateCollectionV2 is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - props *arangodb.CreateCollectionPropertiesV2
func (_e *MockDatabase_Expecter) CreateCollectionV2(ctx interface{}, name interface{}, props interface{}) *MockDatabase_CreateCollectionV2_Call {
	return &MockDatabase_CreateCollectionV2_Call{Call: _e.mock.On("CreateCollectionV2", ctx, name, props)}
}

func (_c *MockDatabase_CreateCollectionV2_Call) Run(run func(ctx context.Context, name string, props *arangodb.CreateCollectionPropertiesV2)) *MockDatabase_CreateCollectionV2_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*arangodb.CreateCollectionPropertiesV2))
	})
	return _c
}

func (_c *MockDatabase_CreateCollectionV2_Call) Return(_a0 arangodb.Collection, _a1 error) *MockDatabase_CreateCollectionV2_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDatabase_CreateCollectionV2_Call) RunAndReturn(run func(context.Context, string, *arangodb.CreateCollectionPropertiesV2) (arangodb.Collection, error)) *MockDatabase_CreateCollectionV2_Call {
	_c.Call.Return(run)
	return _c
}

// CreateCollectionWithOptionsV2 provides a mock function with given fields: ctx, name, props, options
func (_m *MockDatabase) CreateCollectionWithOptionsV2(ctx context.Context, name string, props *arangodb.CreateCollectionPropertiesV2, options *arangodb.CreateCollectionOptions) (arangodb.Collection, error) {
	ret := _m.Called(ctx, name, props, options)

	if len(ret) == 0 {
		panic("no return value specified for CreateCollectionWithOptionsV2")
	}

	var r0 arangodb.Collection
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *arangodb.CreateCollectionPropertiesV2, *arangodb.CreateCollectionOptions) (arangodb.Collection, error)); ok {
		return rf(ctx, name, props, options)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *arangodb.CreateCollectionPropertiesV2, *arangodb.CreateCollectionOptions) arangodb.Collection); ok {
		r0 = rf(ctx, name, props, options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(arangodb.Collection)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *arangodb.CreateCollectionPropertiesV2, *arangodb.CreateCollectionOptions) error); ok {
		r1 = rf(ctx, name, props, options)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDatabase_CreateCollectionWithOptionsV2_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateCollectionWithOptionsV2'
type MockDatabase_CreateCollectionWithOptionsV2_Call struct {
	*mock.Call
}

// CreateCollectionWithOptionsV2 is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - props *arangodb.CreateCollectionPropertiesV2
//   - options *arangodb.CreateCollectionOptions
func (_e *MockDatabase_Expecter) CreateCollectionWithOptionsV2(ctx interface{}, name interface{}, props interface{}, options interface{}) *MockDatabase_CreateCollectionWithOptionsV2_Call {
	return &MockDatabase_CreateCollectionWithOptionsV2_Call{Call: _e.mock.On("CreateCollectionWithOptionsV2", ctx, name, props, options)}
}

func (_c *MockDatabase_CreateCollectionWithOptionsV2_Call) Run(run func(ctx context.Context, name string, props *arangodb.CreateCollectionPropertiesV2, options *arangodb.CreateCollectionOptions)) *MockDatabase_CreateCollectionWithOptionsV2_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*arangodb.CreateCollectionPropertiesV2), args[3].(*arangodb.CreateCollectionOptions))
	})
	return _c
}

func (_c *MockDatabase_CreateCollectionWithOptionsV2_Call) Return(_a0 arangodb.Collection, _a1 error) *MockDatabase_CreateCollectionWithOptionsV2_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDatabase_CreateCollectionWithOptionsV2_Call) RunAndReturn(run func(context.Context, string, *arangodb.CreateCollectionPropertiesV2, *arangodb.CreateCollectionOptions) (arangodb.Collection, error)) *MockDatabase_CreateCollectionWithOptionsV2_Call {
	_c.Call.Return(run)
	return _c
}

// CreateGraph provides a mock function with given fields: ctx, name, graph, options
func (_m *MockDatabase) CreateGraph(ctx context.Context, name string, graph *arangodb.GraphDefinition, options *arangodb.CreateGraphOptions) (arangodb.Graph, error) {
	ret := _m.Called(ctx, name, graph, options)

	if len(ret) == 0 {
		panic("no return value specified for CreateGraph")
	}

	var r0 arangodb.Graph
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *arangodb.GraphDefinition, *arangodb.CreateGraphOptions) (arangodb.Graph, error)); ok {
		return rf(ctx, name, graph, options)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *arangodb.GraphDefinition, *arangodb.CreateGraphOptions) arangodb.Graph); ok {
		r0 = rf(ctx, name, graph, options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(arangodb.Graph)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *arangodb.GraphDefinition, *arangodb.CreateGraphOptions) error); ok {
		r1 = rf(ctx, name, graph, options)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDatabase_CreateGraph_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateGraph'
type MockDatabase_CreateGraph_Call struct {
	*mock.Call
}

// CreateGraph is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - graph *arangodb.GraphDefinition
//   - options *arangodb.CreateGraphOptions
func (_e *MockDatabase_Expecter) CreateGraph(ctx interface{}, name interface{}, graph interface{}, options interface{}) *MockDatabase_CreateGraph_Call {
	return &MockDatabase_CreateGraph_Call{Call: _e.mock.On("CreateGraph", ctx, name, graph, options)}
}

func (_c *MockDatabase_CreateGraph_Call) Run(run func(ctx context.Context, name string, graph *arangodb.GraphDefinition, options *arangodb.CreateGraphOptions)) *MockDatabase_CreateGraph_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*arangodb.GraphDefinition), args[3].(*arangodb.CreateGraphOptions))
	})
	return _c
}

func (_c *MockDatabase_CreateGraph_Call) Return(_a0 arangodb.Graph, _a1 error) *MockDatabase_CreateGraph_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDatabase_CreateGraph_Call) RunAndReturn(run func(context.Context, string, *arangodb.GraphDefinition, *arangodb.CreateGraphOptions) (arangodb.Graph, error)) *MockDatabase_CreateGraph_Call {
	_c.Call.Return(run)
	return _c
}

// CreateUserDefinedFunction provides a mock function with given fields: ctx, options
func (_m *MockDatabase) CreateUserDefinedFunction(ctx context.Context, options arangodb.UserDefinedFunctionObject) (bool, error) {
	ret := _m.Called(ctx, options)

	if len(ret) == 0 {
		panic("no return value specified for CreateUserDefinedFunction")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, arangodb.UserDefinedFunctionObject) (bool, error)); ok {
		return rf(ctx, options)
	}
	if rf, ok := ret.Get(0).(func(context.Context, arangodb.UserDefinedFunctionObject) bool); ok {
		r0 = rf(ctx, options)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, arangodb.UserDefinedFunctionObject) error); ok {
		r1 = rf(ctx, options)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDatabase_CreateUserDefinedFunction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUserDefinedFunction'
type MockDatabase_CreateUserDefinedFunction_Call struct {
	*mock.Call
}

// CreateUserDefinedFunction is a helper method to define mock.On call
//   - ctx context.Context
//   - options arangodb.UserDefinedFunctionObject
func (_e *MockDatabase_Expecter) CreateUserDefinedFunction(ctx interface{}, options interface{}) *MockDatabase_CreateUserDefinedFunction_Call {
	return &MockDatabase_CreateUserDefinedFunction_Call{Call: _e.mock.On("CreateUserDefinedFunction", ctx, options)}
}

func (_c *MockDatabase_CreateUserDefinedFunction_Call) Run(run func(ctx context.Context, options arangodb.UserDefinedFunctionObject)) *MockDatabase_CreateUserDefinedFunction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(arangodb.UserDefinedFunctionObject))
	})
	return _c
}

func (_c *MockDatabase_CreateUserDefinedFunction_Call) Return(_a0 bool, _a1 error) *MockDatabase_CreateUserDefinedFunction_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDatabase_CreateUserDefinedFunction_Call) RunAndReturn(run func(context.Context, arangodb.UserDefinedFunctionObject) (bool, error)) *MockDatabase_CreateUserDefinedFunction_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteUserDefinedFunction provides a mock function with given fields: ctx, name, group
func (_m *MockDatabase) DeleteUserDefinedFunction(ctx context.Context, name *string, group *bool) (*int, error) {
	ret := _m.Called(ctx, name, group)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUserDefinedFunction")
	}

	var r0 *int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *string, *bool) (*int, error)); ok {
		return rf(ctx, name, group)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *string, *bool) *int); ok {
		r0 = rf(ctx, name, group)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*int)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *string, *bool) error); ok {
		r1 = rf(ctx, name, group)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDatabase_DeleteUserDefinedFunction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteUserDefinedFunction'
type MockDatabase_DeleteUserDefinedFunction_Call struct {
	*mock.Call
}

// DeleteUserDefinedFunction is a helper method to define mock.On call
//   - ctx context.Context
//   - name *string
//   - group *bool
func (_e *MockDatabase_Expecter) DeleteUserDefinedFunction(ctx interface{}, name interface{}, group interface{}) *MockDatabase_DeleteUserDefinedFunction_Call {
	return &MockDatabase_DeleteUserDefinedFunction_Call{Call: _e.mock.On("DeleteUserDefinedFunction", ctx, name, group)}
}

func (_c *MockDatabase_DeleteUserDefinedFunction_Call) Run(run func(ctx context.Context, name *string, group *bool)) *MockDatabase_DeleteUserDefinedFunction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*string), args[2].(*bool))
	})
	return _c
}

func (_c *MockDatabase_DeleteUserDefinedFunction_Call) Return(_a0 *int, _a1 error) *MockDatabase_DeleteUserDefinedFunction_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDatabase_DeleteUserDefinedFunction_Call) RunAndReturn(run func(context.Context, *string, *bool) (*int, error)) *MockDatabase_DeleteUserDefinedFunction_Call {
	_c.Call.Return(run)
	return _c
}

// EnsureCreatedAnalyzer provides a mock function with given fields: ctx, analyzer
func (_m *MockDatabase) EnsureCreatedAnalyzer(ctx context.Context, analyzer *arangodb.AnalyzerDefinition) (arangodb.Analyzer, bool, error) {
	ret := _m.Called(ctx, analyzer)

	if len(ret) == 0 {
		panic("no return value specified for EnsureCreatedAnalyzer")
	}

	var r0 arangodb.Analyzer
	var r1 bool
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, *arangodb.AnalyzerDefinition) (arangodb.Analyzer, bool, error)); ok {
		return rf(ctx, analyzer)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *arangodb.AnalyzerDefinition) arangodb.Analyzer); ok {
		r0 = rf(ctx, analyzer)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(arangodb.Analyzer)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *arangodb.AnalyzerDefinition) bool); ok {
		r1 = rf(ctx, analyzer)
	} else {
		r1 = ret.Get(1).(bool)
	}

	if rf, ok := ret.Get(2).(func(context.Context, *arangodb.AnalyzerDefinition) error); ok {
		r2 = rf(ctx, analyzer)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockDatabase_EnsureCreatedAnalyzer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnsureCreatedAnalyzer'
type MockDatabase_EnsureCreatedAnalyzer_Call struct {
	*mock.Call
}

// EnsureCreatedAnalyzer is a helper method to define mock.On call
//   - ctx context.Context
//   - analyzer *arangodb.AnalyzerDefinition
func (_e *MockDatabase_Expecter) EnsureCreatedAnalyzer(ctx interface{}, analyzer interface{}) *MockDatabase_EnsureCreatedAnalyzer_Call {
	return &MockDatabase_EnsureCreatedAnalyzer_Call{Call: _e.mock.On("EnsureCreatedAnalyzer", ctx, analyzer)}
}

func (_c *MockDatabase_EnsureCreatedAnalyzer_Call) Run(run func(ctx context.Context, analyzer *arangodb.AnalyzerDefinition)) *MockDatabase_EnsureCreatedAnalyzer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*arangodb.AnalyzerDefinition))
	})
	return _c
}

func (_c *MockDatabase_EnsureCreatedAnalyzer_Call) Return(_a0 arangodb.Analyzer, _a1 bool, _a2 error) *MockDatabase_EnsureCreatedAnalyzer_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockDatabase_EnsureCreatedAnalyzer_Call) RunAndReturn(run func(context.Context, *arangodb.AnalyzerDefinition) (arangodb.Analyzer, bool, error)) *MockDatabase_EnsureCreatedAnalyzer_Call {
	_c.Call.Return(run)
	return _c
}

// ExplainQuery provides a mock function with given fields: ctx, query, bindVars, opts
func (_m *MockDatabase) ExplainQuery(ctx context.Context, query string, bindVars map[string]interface{}, opts *arangodb.ExplainQueryOptions) (arangodb.ExplainQueryResult, error) {
	ret := _m.Called(ctx, query, bindVars, opts)

	if len(ret) == 0 {
		panic("no return value specified for ExplainQuery")
	}

	var r0 arangodb.ExplainQueryResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, map[string]interface{}, *arangodb.ExplainQueryOptions) (arangodb.ExplainQueryResult, error)); ok {
		return rf(ctx, query, bindVars, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, map[string]interface{}, *arangodb.ExplainQueryOptions) arangodb.ExplainQueryResult); ok {
		r0 = rf(ctx, query, bindVars, opts)
	} else {
		r0 = ret.Get(0).(arangodb.ExplainQueryResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, map[string]interface{}, *arangodb.ExplainQueryOptions) error); ok {
		r1 = rf(ctx, query, bindVars, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDatabase_ExplainQuery_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExplainQuery'
type MockDatabase_ExplainQuery_Call struct {
	*mock.Call
}

// ExplainQuery is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
//   - bindVars map[string]interface{}
//   - opts *arangodb.ExplainQueryOptions
func (_e *MockDatabase_Expecter) ExplainQuery(ctx interface{}, query interface{}, bindVars interface{}, opts interface{}) *MockDatabase_ExplainQuery_Call {
	return &MockDatabase_ExplainQuery_Call{Call: _e.mock.On("ExplainQuery", ctx, query, bindVars, opts)}
}

func (_c *MockDatabase_ExplainQuery_Call) Run(run func(ctx context.Context, query string, bindVars map[string]interface{}, opts *arangodb.ExplainQueryOptions)) *MockDatabase_ExplainQuery_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(map[string]interface{}), args[3].(*arangodb.ExplainQueryOptions))
	})
	return _c
}

func (_c *MockDatabase_ExplainQuery_Call) Return(_a0 arangodb.ExplainQueryResult, _a1 error) *MockDatabase_ExplainQuery_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDatabase_ExplainQuery_Call) RunAndReturn(run func(context.Context, string, map[string]interface{}, *arangodb.ExplainQueryOptions) (arangodb.ExplainQueryResult, error)) *MockDatabase_ExplainQuery_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllOptimizerRules provides a mock function with given fields: ctx
func (_m *MockDatabase) GetAllOptimizerRules(ctx context.Context) ([]arangodb.OptimizerRules, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllOptimizerRules")
	}

	var r0 []arangodb.OptimizerRules
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]arangodb.OptimizerRules, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []arangodb.OptimizerRules); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]arangodb.OptimizerRules)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDatabase_GetAllOptimizerRules_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllOptimizerRules'
type MockDatabase_GetAllOptimizerRules_Call struct {
	*mock.Call
}

// GetAllOptimizerRules is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockDatabase_Expecter) GetAllOptimizerRules(ctx interface{}) *MockDatabase_GetAllOptimizerRules_Call {
	return &MockDatabase_GetAllOptimizerRules_Call{Call: _e.mock.On("GetAllOptimizerRules", ctx)}
}

func (_c *MockDatabase_GetAllOptimizerRules_Call) Run(run func(ctx context.Context)) *MockDatabase_GetAllOptimizerRules_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockDatabase_GetAllOptimizerRules_Call) Return(_a0 []arangodb.OptimizerRules, _a1 error) *MockDatabase_GetAllOptimizerRules_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDatabase_GetAllOptimizerRules_Call) RunAndReturn(run func(context.Context) ([]arangodb.OptimizerRules, error)) *MockDatabase_GetAllOptimizerRules_Call {
	_c.Call.Return(run)
	return _c
}

// GetCollection provides a mock function with given fields: ctx, name, options
func (_m *MockDatabase) GetCollection(ctx context.Context, name string, options *arangodb.GetCollectionOptions) (arangodb.Collection, error) {
	ret := _m.Called(ctx, name, options)

	if len(ret) == 0 {
		panic("no return value specified for GetCollection")
	}

	var r0 arangodb.Collection
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *arangodb.GetCollectionOptions) (arangodb.Collection, error)); ok {
		return rf(ctx, name, options)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *arangodb.GetCollectionOptions) arangodb.Collection); ok {
		r0 = rf(ctx, name, options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(arangodb.Collection)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *arangodb.GetCollectionOptions) error); ok {
		r1 = rf(ctx, name, options)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDatabase_GetCollection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCollection'
type MockDatabase_GetCollection_Call struct {
	*mock.Call
}

// GetCollection is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - options *arangodb.GetCollectionOptions
func (_e *MockDatabase_Expecter) GetCollection(ctx interface{}, name interface{}, options interface{}) *MockDatabase_GetCollection_Call {
	return &MockDatabase_GetCollection_Call{Call: _e.mock.On("GetCollection", ctx, name, options)}
}

func (_c *MockDatabase_GetCollection_Call) Run(run func(ctx context.Context, name string, options *arangodb.GetCollectionOptions)) *MockDatabase_GetCollection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*arangodb.GetCollectionOptions))
	})
	return _c
}

func (_c *MockDatabase_GetCollection_Call) Return(_a0 arangodb.Collection, _a1 error) *MockDatabase_GetCollection_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDatabase_GetCollection_Call) RunAndReturn(run func(context.Context, string, *arangodb.GetCollectionOptions) (arangodb.Collection, error)) *MockDatabase_GetCollection_Call {
	_c.Call.Return(run)
	return _c
}

// GetEdges provides a mock function with given fields: ctx, name, vertex, options
func (_m *MockDatabase) GetEdges(ctx context.Context, name string, vertex string, options *arangodb.GetEdgesOptions) ([]arangodb.EdgeDetails, error) {
	ret := _m.Called(ctx, name, vertex, options)

	if len(ret) == 0 {
		panic("no return value specified for GetEdges")
	}

	var r0 []arangodb.EdgeDetails
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *arangodb.GetEdgesOptions) ([]arangodb.EdgeDetails, error)); ok {
		return rf(ctx, name, vertex, options)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *arangodb.GetEdgesOptions) []arangodb.EdgeDetails); ok {
		r0 = rf(ctx, name, vertex, options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]arangodb.EdgeDetails)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, *arangodb.GetEdgesOptions) error); ok {
		r1 = rf(ctx, name, vertex, options)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDatabase_GetEdges_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEdges'
type MockDatabase_GetEdges_Call struct {
	*mock.Call
}

// GetEdges is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - vertex string
//   - options *arangodb.GetEdgesOptions
func (_e *MockDatabase_Expecter) GetEdges(ctx interface{}, name interface{}, vertex interface{}, options interface{}) *MockDatabase_GetEdges_Call {
	return &MockDatabase_GetEdges_Call{Call: _e.mock.On("GetEdges", ctx, name, vertex, options)}
}

func (_c *MockDatabase_GetEdges_Call) Run(run func(ctx context.Context, name string, vertex string, options *arangodb.GetEdgesOptions)) *MockDatabase_GetEdges_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(*arangodb.GetEdgesOptions))
	})
	return _c
}

func (_c *MockDatabase_GetEdges_Call) Return(_a0 []arangodb.EdgeDetails, _a1 error) *MockDatabase_GetEdges_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDatabase_GetEdges_Call) RunAndReturn(run func(context.Context, string, string, *arangodb.GetEdgesOptions) ([]arangodb.EdgeDetails, error)) *MockDatabase_GetEdges_Call {
	_c.Call.Return(run)
	return _c
}

// GetQueryCacheProperties provides a mock function with given fields: ctx
func (_m *MockDatabase) GetQueryCacheProperties(ctx context.Context) (arangodb.QueryCacheProperties, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetQueryCacheProperties")
	}

	var r0 arangodb.QueryCacheProperties
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (arangodb.QueryCacheProperties, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) arangodb.QueryCacheProperties); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(arangodb.QueryCacheProperties)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDatabase_GetQueryCacheProperties_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetQueryCacheProperties'
type MockDatabase_GetQueryCacheProperties_Call struct {
	*mock.Call
}

// GetQueryCacheProperties is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockDatabase_Expecter) GetQueryCacheProperties(ctx interface{}) *MockDatabase_GetQueryCacheProperties_Call {
	return &MockDatabase_GetQueryCacheProperties_Call{Call: _e.mock.On("GetQueryCacheProperties", ctx)}
}

func (_c *MockDatabase_GetQueryCacheProperties_Call) Run(run func(ctx context.Context)) *MockDatabase_GetQueryCacheProperties_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockDatabase_GetQueryCacheProperties_Call) Return(_a0 arangodb.QueryCacheProperties, _a1 error) *MockDatabase_GetQueryCacheProperties_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDatabase_GetQueryCacheProperties_Call) RunAndReturn(run func(context.Context) (arangodb.QueryCacheProperties, error)) *MockDatabase_GetQueryCacheProperties_Call {
	_c.Call.Return(run)
	return _c
}

// GetQueryEntriesCache provides a mock function with given fields: ctx
func (_m *MockDatabase) GetQueryEntriesCache(ctx context.Context) ([]arangodb.QueryCacheEntriesRespObject, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetQueryEntriesCache")
	}

	var r0 []arangodb.QueryCacheEntriesRespObject
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]arangodb.QueryCacheEntriesRespObject, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []arangodb.QueryCacheEntriesRespObject); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]arangodb.QueryCacheEntriesRespObject)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDatabase_GetQueryEntriesCache_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetQueryEntriesCache'
type MockDatabase_GetQueryEntriesCache_Call struct {
	*mock.Call
}

// GetQueryEntriesCache is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockDatabase_Expecter) GetQueryEntriesCache(ctx interface{}) *MockDatabase_GetQueryEntriesCache_Call {
	return &MockDatabase_GetQueryEntriesCache_Call{Call: _e.mock.On("GetQueryEntriesCache", ctx)}
}

func (_c *MockDatabase_GetQueryEntriesCache_Call) Run(run func(ctx context.Context)) *MockDatabase_GetQueryEntriesCache_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockDatabase_GetQueryEntriesCache_Call) Return(_a0 []arangodb.QueryCacheEntriesRespObject, _a1 error) *MockDatabase_GetQueryEntriesCache_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDatabase_GetQueryEntriesCache_Call) RunAndReturn(run func(context.Context) ([]arangodb.QueryCacheEntriesRespObject, error)) *MockDatabase_GetQueryEntriesCache_Call {
	_c.Call.Return(run)
	return _c
}

// GetQueryPlanCache provides a mock function with given fields: ctx
func (_m *MockDatabase) GetQueryPlanCache(ctx context.Context) ([]arangodb.QueryPlanCacheRespObject, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetQueryPlanCache")
	}

	var r0 []arangodb.QueryPlanCacheRespObject
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]arangodb.QueryPlanCacheRespObject, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []arangodb.QueryPlanCacheRespObject); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]arangodb.QueryPlanCacheRespObject)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDatabase_GetQueryPlanCache_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetQueryPlanCache'
type MockDatabase_GetQueryPlanCache_Call struct {
	*mock.Call
}

// GetQueryPlanCache is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockDatabase_Expecter) GetQueryPlanCache(ctx interface{}) *MockDatabase_GetQueryPlanCache_Call {
	return &MockDatabase_GetQueryPlanCache_Call{Call: _e.mock.On("GetQueryPlanCache", ctx)}
}

func (_c *MockDatabase_GetQueryPlanCache_Call) Run(run func(ctx context.Context)) *MockDatabase_GetQueryPlanCache_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockDatabase_GetQueryPlanCache_Call) Return(_a0 []arangodb.QueryPlanCacheRespObject, _a1 error) *MockDatabase_GetQueryPlanCache_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDatabase_GetQueryPlanCache_Call) RunAndReturn(run func(context.Context) ([]arangodb.QueryPlanCacheRespObject, error)) *MockDatabase_GetQueryPlanCache_Call {
	_c.Call.Return(run)
	return _c
}

// GetQueryProperties provides a mock function with given fields: ctx
func (_m *MockDatabase) GetQueryProperties(ctx context.Context) (arangodb.QueryProperties, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetQueryProperties")
	}

	var r0 arangodb.QueryProperties
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (arangodb.QueryProperties, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) arangodb.QueryProperties); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(arangodb.QueryProperties)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDatabase_GetQueryProperties_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetQueryProperties'
type MockDatabase_GetQueryProperties_Call struct {
	*mock.Call
}

// GetQueryProperties is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockDatabase_Expecter) GetQueryProperties(ctx interface{}) *MockDatabase_GetQueryProperties_Call {
	return &MockDatabase_GetQueryProperties_Call{Call: _e.mock.On("GetQueryProperties", ctx)}
}

func (_c *MockDatabase_GetQueryProperties_Call) Run(run func(ctx context.Context)) *MockDatabase_GetQueryProperties_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockDatabase_GetQueryProperties_Call) Return(_a0 arangodb.QueryProperties, _a1 error) *MockDatabase_GetQueryProperties_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDatabase_GetQueryProperties_Call) RunAndReturn(run func(context.Context) (arangodb.QueryProperties, error)) *MockDatabase_GetQueryProperties_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserDefinedFunctions provides a mock function with given fields: ctx
func (_m *MockDatabase) GetUserDefinedFunctions(ctx context.Context) ([]arangodb.UserDefinedFunctionObject, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetUserDefinedFunctions")
	}

	var r0 []arangodb.UserDefinedFunctionObject
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]arangodb.UserDefinedFunctionObject, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []arangodb.UserDefinedFunctionObject); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]arangodb.UserDefinedFunctionObject)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDatabase_GetUserDefinedFunctions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserDefinedFunctions'
type MockDatabase_GetUserDefinedFunctions_Call struct {
	*mock.Call
}

// GetUserDefinedFunctions is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockDatabase_Expecter) GetUserDefinedFunctions(ctx interface{}) *MockDatabase_GetUserDefinedFunctions_Call {
	return &MockDatabase_GetUserDefinedFunctions_Call{Call: _e.mock.On("GetUserDefinedFunctions", ctx)}
}

func (_c *MockDatabase_GetUserDefinedFunctions_Call) Run(run func(ctx context.Context)) *MockDatabase_GetUserDefinedFunctions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockDatabase_GetUserDefinedFunctions_Call) Return(_a0 []arangodb.UserDefinedFunctionObject, _a1 error) *MockDatabase_GetUserDefinedFunctions_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDatabase_GetUserDefinedFunctions_Call) RunAndReturn(run func(context.Context) ([]arangodb.UserDefinedFunctionObject, error)) *MockDatabase_GetUserDefinedFunctions_Call {
	_c.Call.Return(run)
	return _c
}

// Graph provides a mock function with given fields: ctx, name, options
func (_m *MockDatabase) Graph(ctx context.Context, name string, options *arangodb.GetGraphOptions) (arangodb.Graph, error) {
	ret := _m.Called(ctx, name, options)

	if len(ret) == 0 {
		panic("no return value specified for Graph")
	}

	var r0 arangodb.Graph
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *arangodb.GetGraphOptions) (arangodb.Graph, error)); ok {
		return rf(ctx, name, options)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *arangodb.GetGraphOptions) arangodb.Graph); ok {
		r0 = rf(ctx, name, options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(arangodb.Graph)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *arangodb.GetGraphOptions) error); ok {
		r1 = rf(ctx, name, options)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDatabase_Graph_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Graph'
type MockDatabase_Graph_Call struct {
	*mock.Call
}

// Graph is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - options *arangodb.GetGraphOptions
func (_e *MockDatabase_Expecter) Graph(ctx interface{}, name interface{}, options interface{}) *MockDatabase_Graph_Call {
	return &MockDatabase_Graph_Call{Call: _e.mock.On("Graph", ctx, name, options)}
}

func (_c *MockDatabase_Graph_Call) Run(run func(ctx context.Context, name string, options *arangodb.GetGraphOptions)) *MockDatabase_Graph_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*arangodb.GetGraphOptions))
	})
	return _c
}

func (_c *MockDatabase_Graph_Call) Return(_a0 arangodb.Graph, _a1 error) *MockDatabase_Graph_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDatabase_Graph_Call) RunAndReturn(run func(context.Context, string, *arangodb.GetGraphOptions) (arangodb.Graph, error)) *MockDatabase_Graph_Call {
	_c.Call.Return(run)
	return _c
}

// GraphExists provides a mock function with given fields: ctx, name
func (_m *MockDatabase) GraphExists(ctx context.Context, name string) (bool, error) {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for GraphExists")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(ctx, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, name)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDatabase_GraphExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GraphExists'
type MockDatabase_GraphExists_Call struct {
	*mock.Call
}

// GraphExists is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockDatabase_Expecter) GraphExists(ctx interface{}, name interface{}) *MockDatabase_GraphExists_Call {
	return &MockDatabase_GraphExists_Call{Call: _e.mock.On("GraphExists", ctx, name)}
}

func (_c *MockDatabase_GraphExists_Call) Run(run func(ctx context.Context, name string)) *MockDatabase_GraphExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockDatabase_GraphExists_Call) Return(_a0 bool, _a1 error) *MockDatabase_GraphExists_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDatabase_GraphExists_Call) RunAndReturn(run func(context.Context, string) (bool, error)) *MockDatabase_GraphExists_Call {
	_c.Call.Return(run)
	return _c
}

// Graphs provides a mock function with given fields: ctx
func (_m *MockDatabase) Graphs(ctx context.Context) (arangodb.GraphsResponseReader, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Graphs")
	}

	var r0 arangodb.GraphsResponseReader
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (arangodb.GraphsResponseReader, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) arangodb.GraphsResponseReader); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(arangodb.GraphsResponseReader)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDatabase_Graphs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Graphs'
type MockDatabase_Graphs_Call struct {
	*mock.Call
}

// Graphs is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockDatabase_Expecter) Graphs(ctx interface{}) *MockDatabase_Graphs_Call {
	return &MockDatabase_Graphs_Call{Call: _e.mock.On("Graphs", ctx)}
}

func (_c *MockDatabase_Graphs_Call) Run(run func(ctx context.Context)) *MockDatabase_Graphs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockDatabase_Graphs_Call) Return(_a0 arangodb.GraphsResponseReader, _a1 error) *MockDatabase_Graphs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDatabase_Graphs_Call) RunAndReturn(run func(context.Context) (arangodb.GraphsResponseReader, error)) *MockDatabase_Graphs_Call {
	_c.Call.Return(run)
	return _c
}

// Info provides a mock function with given fields: ctx
func (_m *MockDatabase) Info(ctx context.Context) (arangodb.DatabaseInfo, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Info")
	}

	var r0 arangodb.DatabaseInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (arangodb.DatabaseInfo, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) arangodb.DatabaseInfo); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(arangodb.DatabaseInfo)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDatabase_Info_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Info'
type MockDatabase_Info_Call struct {
	*mock.Call
}

// Info is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockDatabase_Expecter) Info(ctx interface{}) *MockDatabase_Info_Call {
	return &MockDatabase_Info_Call{Call: _e.mock.On("Info", ctx)}
}

func (_c *MockDatabase_Info_Call) Run(run func(ctx context.Context)) *MockDatabase_Info_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockDatabase_Info_Call) Return(_a0 arangodb.DatabaseInfo, _a1 error) *MockDatabase_Info_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDatabase_Info_Call) RunAndReturn(run func(context.Context) (arangodb.DatabaseInfo, error)) *MockDatabase_Info_Call {
	_c.Call.Return(run)
	return _c
}

// KeyGenerators provides a mock function with given fields: ctx
func (_m *MockDatabase) KeyGenerators(ctx context.Context) (arangodb.KeyGeneratorsResponse, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for KeyGenerators")
	}

	var r0 arangodb.KeyGeneratorsResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (arangodb.KeyGeneratorsResponse, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) arangodb.KeyGeneratorsResponse); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(arangodb.KeyGeneratorsResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDatabase_KeyGenerators_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'KeyGenerators'
type MockDatabase_KeyGenerators_Call struct {
	*mock.Call
}

// KeyGenerators is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockDatabase_Expecter) KeyGenerators(ctx interface{}) *MockDatabase_KeyGenerators_Call {
	return &MockDatabase_KeyGenerators_Call{Call: _e.mock.On("KeyGenerators", ctx)}
}

func (_c *MockDatabase_KeyGenerators_Call) Run(run func(ctx context.Context)) *MockDatabase_KeyGenerators_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockDatabase_KeyGenerators_Call) Return(_a0 arangodb.KeyGeneratorsResponse, _a1 error) *MockDatabase_KeyGenerators_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDatabase_KeyGenerators_Call) RunAndReturn(run func(context.Context) (arangodb.KeyGeneratorsResponse, error)) *MockDatabase_KeyGenerators_Call {
	_c.Call.Return(run)
	return _c
}

// KillAQLQuery provides a mock function with given fields: ctx, queryId, all
func (_m *MockDatabase) KillAQLQuery(ctx context.Context, queryId string, all *bool) error {
	ret := _m.Called(ctx, queryId, all)

	if len(ret) == 0 {
		panic("no return value specified for KillAQLQuery")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *bool) error); ok {
		r0 = rf(ctx, queryId, all)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockDatabase_KillAQLQuery_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'KillAQLQuery'
type MockDatabase_KillAQLQuery_Call struct {
	*mock.Call
}

// KillAQLQuery is a helper method to define mock.On call
//   - ctx context.Context
//   - queryId string
//   - all *bool
func (_e *MockDatabase_Expecter) KillAQLQuery(ctx interface{}, queryId interface{}, all interface{}) *MockDatabase_KillAQLQuery_Call {
	return &MockDatabase_KillAQLQuery_Call{Call: _e.mock.On("KillAQLQuery", ctx, queryId, all)}
}

func (_c *MockDatabase_KillAQLQuery_Call) Run(run func(ctx context.Context, queryId string, all *bool)) *MockDatabase_KillAQLQuery_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*bool))
	})
	return _c
}

func (_c *MockDatabase_KillAQLQuery_Call) Return(_a0 error) *MockDatabase_KillAQLQuery_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDatabase_KillAQLQuery_Call) RunAndReturn(run func(context.Context, string, *bool) error) *MockDatabase_KillAQLQuery_Call {
	_c.Call.Return(run)
	return _c
}

// ListOfRunningAQLQueries provides a mock function with given fields: ctx, all
func (_m *MockDatabase) ListOfRunningAQLQueries(ctx context.Context, all *bool) ([]arangodb.RunningAQLQuery, error) {
	ret := _m.Called(ctx, all)

	if len(ret) == 0 {
		panic("no return value specified for ListOfRunningAQLQueries")
	}

	var r0 []arangodb.RunningAQLQuery
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *bool) ([]arangodb.RunningAQLQuery, error)); ok {
		return rf(ctx, all)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *bool) []arangodb.RunningAQLQuery); ok {
		r0 = rf(ctx, all)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]arangodb.RunningAQLQuery)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *bool) error); ok {
		r1 = rf(ctx, all)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDatabase_ListOfRunningAQLQueries_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListOfRunningAQLQueries'
type MockDatabase_ListOfRunningAQLQueries_Call struct {
	*mock.Call
}

// ListOfRunningAQLQueries is a helper method to define mock.On call
//   - ctx context.Context
//   - all *bool
func (_e *MockDatabase_Expecter) ListOfRunningAQLQueries(ctx interface{}, all interface{}) *MockDatabase_ListOfRunningAQLQueries_Call {
	return &MockDatabase_ListOfRunningAQLQueries_Call{Call: _e.mock.On("ListOfRunningAQLQueries", ctx, all)}
}

func (_c *MockDatabase_ListOfRunningAQLQueries_Call) Run(run func(ctx context.Context, all *bool)) *MockDatabase_ListOfRunningAQLQueries_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*bool))
	})
	return _c
}

func (_c *MockDatabase_ListOfRunningAQLQueries_Call) Return(_a0 []arangodb.RunningAQLQuery, _a1 error) *MockDatabase_ListOfRunningAQLQueries_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDatabase_ListOfRunningAQLQueries_Call) RunAndReturn(run func(context.Context, *bool) ([]arangodb.RunningAQLQuery, error)) *MockDatabase_ListOfRunningAQLQueries_Call {
	_c.Call.Return(run)
	return _c
}

// ListOfSlowAQLQueries provides a mock function with given fields: ctx, all
func (_m *MockDatabase) ListOfSlowAQLQueries(ctx context.Context, all *bool) ([]arangodb.RunningAQLQuery, error) {
	ret := _m.Called(ctx, all)

	if len(ret) == 0 {
		panic("no return value specified for ListOfSlowAQLQueries")
	}

	var r0 []arangodb.RunningAQLQuery
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *bool) ([]arangodb.RunningAQLQuery, error)); ok {
		return rf(ctx, all)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *bool) []arangodb.RunningAQLQuery); ok {
		r0 = rf(ctx, all)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]arangodb.RunningAQLQuery)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *bool) error); ok {
		r1 = rf(ctx, all)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDatabase_ListOfSlowAQLQueries_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListOfSlowAQLQueries'
type MockDatabase_ListOfSlowAQLQueries_Call struct {
	*mock.Call
}

// ListOfSlowAQLQueries is a helper method to define mock.On call
//   - ctx context.Context
//   - all *bool
func (_e *MockDatabase_Expecter) ListOfSlowAQLQueries(ctx interface{}, all interface{}) *MockDatabase_ListOfSlowAQLQueries_Call {
	return &MockDatabase_ListOfSlowAQLQueries_Call{Call: _e.mock.On("ListOfSlowAQLQueries", ctx, all)}
}

func (_c *MockDatabase_ListOfSlowAQLQueries_Call) Run(run func(ctx context.Context, all *bool)) *MockDatabase_ListOfSlowAQLQueries_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*bool))
	})
	return _c
}

func (_c *MockDatabase_ListOfSlowAQLQueries_Call) Return(_a0 []arangodb.RunningAQLQuery, _a1 error) *MockDatabase_ListOfSlowAQLQueries_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDatabase_ListOfSlowAQLQueries_Call) RunAndReturn(run func(context.Context, *bool) ([]arangodb.RunningAQLQuery, error)) *MockDatabase_ListOfSlowAQLQueries_Call {
	_c.Call.Return(run)
	return _c
}

// ListTransactions provides a mock function with given fields: ctx
func (_m *MockDatabase) ListTransactions(ctx context.Context) ([]arangodb.Transaction, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListTransactions")
	}

	var r0 []arangodb.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]arangodb.Transaction, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []arangodb.Transaction); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]arangodb.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDatabase_ListTransactions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTransactions'
type MockDatabase_ListTransactions_Call struct {
	*mock.Call
}

// ListTransactions is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockDatabase_Expecter) ListTransactions(ctx interface{}) *MockDatabase_ListTransactions_Call {
	return &MockDatabase_ListTransactions_Call{Call: _e.mock.On("ListTransactions", ctx)}
}

func (_c *MockDatabase_ListTransactions_Call) Run(run func(ctx context.Context)) *MockDatabase_ListTransactions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockDatabase_ListTransactions_Call) Return(_a0 []arangodb.Transaction, _a1 error) *MockDatabase_ListTransactions_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDatabase_ListTransactions_Call) RunAndReturn(run func(context.Context) ([]arangodb.Transaction, error)) *MockDatabase_ListTransactions_Call {
	_c.Call.Return(run)
	return _c
}

// ListTransactionsWithStatuses provides a mock function with given fields: ctx, statuses
func (_m *MockDatabase) ListTransactionsWithStatuses(ctx context.Context, statuses ...arangodb.TransactionStatus) ([]arangodb.Transaction, error) {
	_va := make([]interface{}, len(statuses))
	for _i := range statuses {
		_va[_i] = statuses[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ListTransactionsWithStatuses")
	}

	var r0 []arangodb.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ...arangodb.TransactionStatus) ([]arangodb.Transaction, error)); ok {
		return rf(ctx, statuses...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ...arangodb.TransactionStatus) []arangodb.Transaction); ok {
		r0 = rf(ctx, statuses...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]arangodb.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, ...arangodb.TransactionStatus) error); ok {
		r1 = rf(ctx, statuses...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDatabase_ListTransactionsWithStatuses_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTransactionsWithStatuses'
type MockDatabase_ListTransactionsWithStatuses_Call struct {
	*mock.Call
}

// ListTransactionsWithStatuses is a helper method to define mock.On call
//   - ctx context.Context
//   - statuses ...arangodb.TransactionStatus
func (_e *MockDatabase_Expecter) ListTransactionsWithStatuses(ctx interface{}, statuses ...interface{}) *MockDatabase_ListTransactionsWithStatuses_Call {
	return &MockDatabase_ListTransactionsWithStatuses_Call{Call: _e.mock.On("ListTransactionsWithStatuses",
		append([]interface{}{ctx}, statuses...)...)}
}

func (_c *MockDatabase_ListTransactionsWithStatuses_Call) Run(run func(ctx context.Context, statuses ...arangodb.TransactionStatus)) *MockDatabase_ListTransactionsWithStatuses_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]arangodb.TransactionStatus, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(arangodb.TransactionStatus)
			}
		}
		run(args[0].(context.Context), variadicArgs...)
	})
	return _c
}

func (_c *MockDatabase_ListTransactionsWithStatuses_Call) Return(_a0 []arangodb.Transaction, _a1 error) *MockDatabase_ListTransactionsWithStatuses_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDatabase_ListTransactionsWithStatuses_Call) RunAndReturn(run func(context.Context, ...arangodb.TransactionStatus) ([]arangodb.Transaction, error)) *MockDatabase_ListTransactionsWithStatuses_Call {
	_c.Call.Return(run)
	return _c
}

// Name provides a mock function with no fields
func (_m *MockDatabase) Name() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockDatabase_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type MockDatabase_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *MockDatabase_Expecter) Name() *MockDatabase_Name_Call {
	return &MockDatabase_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *MockDatabase_Name_Call) Run(run func()) *MockDatabase_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDatabase_Name_Call) Return(_a0 string) *MockDatabase_Name_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDatabase_Name_Call) RunAndReturn(run func() string) *MockDatabase_Name_Call {
	_c.Call.Return(run)
	return _c
}

// Query provides a mock function with given fields: ctx, query, opts
func (_m *MockDatabase) Query(ctx context.Context, query string, opts *arangodb.QueryOptions) (arangodb.Cursor, error) {
	ret := _m.Called(ctx, query, opts)

	if len(ret) == 0 {
		panic("no return value specified for Query")
	}

	var r0 arangodb.Cursor
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *arangodb.QueryOptions) (arangodb.Cursor, error)); ok {
		return rf(ctx, query, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *arangodb.QueryOptions) arangodb.Cursor); ok {
		r0 = rf(ctx, query, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(arangodb.Cursor)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *arangodb.QueryOptions) error); ok {
		r1 = rf(ctx, query, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDatabase_Query_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Query'
type MockDatabase_Query_Call struct {
	*mock.Call
}

// Query is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
//   - opts *arangodb.QueryOptions
func (_e *MockDatabase_Expecter) Query(ctx interface{}, query interface{}, opts interface{}) *MockDatabase_Query_Call {
	return &MockDatabase_Query_Call{Call: _e.mock.On("Query", ctx, query, opts)}
}

func (_c *MockDatabase_Query_Call) Run(run func(ctx context.Context, query string, opts *arangodb.QueryOptions)) *MockDatabase_Query_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*arangodb.QueryOptions))
	})
	return _c
}

func (_c *MockDatabase_Query_Call) Return(_a0 arangodb.Cursor, _a1 error) *MockDatabase_Query_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDatabase_Query_Call) RunAndReturn(run func(context.Context, string, *arangodb.QueryOptions) (arangodb.Cursor, error)) *MockDatabase_Query_Call {
	_c.Call.Return(run)
	return _c
}

// QueryBatch provides a mock function with given fields: ctx, query, opts, result
func (_m *MockDatabase) QueryBatch(ctx context.Context, query string, opts *arangodb.QueryOptions, result interface{}) (arangodb.CursorBatch, error) {
	ret := _m.Called(ctx, query, opts, result)

	if len(ret) == 0 {
		panic("no return value specified for QueryBatch")
	}

	var r0 arangodb.CursorBatch
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *arangodb.QueryOptions, interface{}) (arangodb.CursorBatch, error)); ok {
		return rf(ctx, query, opts, result)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *arangodb.QueryOptions, interface{}) arangodb.CursorBatch); ok {
		r0 = rf(ctx, query, opts, result)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(arangodb.CursorBatch)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *arangodb.QueryOptions, interface{}) error); ok {
		r1 = rf(ctx, query, opts, result)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDatabase_QueryBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueryBatch'
type MockDatabase_QueryBatch_Call struct {
	*mock.Call
}

// QueryBatch is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
//   - opts *arangodb.QueryOptions
//   - result interface{}
func (_e *MockDatabase_Expecter) QueryBatch(ctx interface{}, query interface{}, opts interface{}, result interface{}) *MockDatabase_QueryBatch_Call {
	return &MockDatabase_QueryBatch_Call{Call: _e.mock.On("QueryBatch", ctx, query, opts, result)}
}

func (_c *MockDatabase_QueryBatch_Call) Run(run func(ctx context.Context, query string, opts *arangodb.QueryOptions, result interface{})) *MockDatabase_QueryBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*arangodb.QueryOptions), args[3].(interface{}))
	})
	return _c
}

func (_c *MockDatabase_QueryBatch_Call) Return(_a0 arangodb.CursorBatch, _a1 error) *MockDatabase_QueryBatch_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDatabase_QueryBatch_Call) RunAndReturn(run func(context.Context, string, *arangodb.QueryOptions, interface{}) (arangodb.CursorBatch, error)) *MockDatabase_QueryBatch_Call {
	_c.Call.Return(run)
	return _c
}

// Remove provides a mock function with given fields: ctx
func (_m *MockDatabase) Remove(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Remove")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockDatabase_Remove_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Remove'
type MockDatabase_Remove_Call struct {
	*mock.Call
}

// Remove is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockDatabase_Expecter) Remove(ctx interface{}) *MockDatabase_Remove_Call {
	return &MockDatabase_Remove_Call{Call: _e.mock.On("Remove", ctx)}
}

func (_c *MockDatabase_Remove_Call) Run(run func(ctx context.Context)) *MockDatabase_Remove_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockDatabase_Remove_Call) Return(_a0 error) *MockDatabase_Remove_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDatabase_Remove_Call) RunAndReturn(run func(context.Context) error) *MockDatabase_Remove_Call {
	_c.Call.Return(run)
	return _c
}

// SetQueryCacheProperties provides a mock function with given fields: ctx, options
func (_m *MockDatabase) SetQueryCacheProperties(ctx context.Context, options arangodb.QueryCacheProperties) (arangodb.QueryCacheProperties, error) {
	ret := _m.Called(ctx, options)

	if len(ret) == 0 {
		panic("no return value specified for SetQueryCacheProperties")
	}

	var r0 arangodb.QueryCacheProperties
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, arangodb.QueryCacheProperties) (arangodb.QueryCacheProperties, error)); ok {
		return rf(ctx, options)
	}
	if rf, ok := ret.Get(0).(func(context.Context, arangodb.QueryCacheProperties) arangodb.QueryCacheProperties); ok {
		r0 = rf(ctx, options)
	} else {
		r0 = ret.Get(0).(arangodb.QueryCacheProperties)
	}

	if rf, ok := ret.Get(1).(func(context.Context, arangodb.QueryCacheProperties) error); ok {
		r1 = rf(ctx, options)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDatabase_SetQueryCacheProperties_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetQueryCacheProperties'
type MockDatabase_SetQueryCacheProperties_Call struct {
	*mock.Call
}

// SetQueryCacheProperties is a helper method to define mock.On call
//   - ctx context.Context
//   - options arangodb.QueryCacheProperties
func (_e *MockDatabase_Expecter) SetQueryCacheProperties(ctx interface{}, options interface{}) *MockDatabase_SetQueryCacheProperties_Call {
	return &MockDatabase_SetQueryCacheProperties_Call{Call: _e.mock.On("SetQueryCacheProperties", ctx, options)}
}

func (_c *MockDatabase_SetQueryCacheProperties_Call) Run(run func(ctx context.Context, options arangodb.QueryCacheProperties)) *MockDatabase_SetQueryCacheProperties_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(arangodb.QueryCacheProperties))
	})
	return _c
}

func (_c *MockDatabase_SetQueryCacheProperties_Call) Return(_a0 arangodb.QueryCacheProperties, _a1 error) *MockDatabase_SetQueryCacheProperties_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDatabase_SetQueryCacheProperties_Call) RunAndReturn(run func(context.Context, arangodb.QueryCacheProperties) (arangodb.QueryCacheProperties, error)) *MockDatabase_SetQueryCacheProperties_Call {
	_c.Call.Return(run)
	return _c
}

// Transaction provides a mock function with given fields: ctx, id
func (_m *MockDatabase) Transaction(ctx context.Context, id arangodb.TransactionID) (arangodb.Transaction, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Transaction")
	}

	var r0 arangodb.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, arangodb.TransactionID) (arangodb.Transaction, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, arangodb.TransactionID) arangodb.Transaction); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(arangodb.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, arangodb.TransactionID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDatabase_Transaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Transaction'
type MockDatabase_Transaction_Call struct {
	*mock.Call
}

// Transaction is a helper method to define mock.On call
//   - ctx context.Context
//   - id arangodb.TransactionID
func (_e *MockDatabase_Expecter) Transaction(ctx interface{}, id interface{}) *MockDatabase_Transaction_Call {
	return &MockDatabase_Transaction_Call{Call: _e.mock.On("Transaction", ctx, id)}
}

func (_c *MockDatabase_Transaction_Call) Run(run func(ctx context.Context, id arangodb.TransactionID)) *MockDatabase_Transaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(arangodb.TransactionID))
	})
	return _c
}

func (_c *MockDatabase_Transaction_Call) Return(_a0 arangodb.Transaction, _a1 error) *MockDatabase_Transaction_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDatabase_Transaction_Call) RunAndReturn(run func(context.Context, arangodb.TransactionID) (arangodb.Transaction, error)) *MockDatabase_Transaction_Call {
	_c.Call.Return(run)
	return _c
}

// TransactionJS provides a mock function with given fields: ctx, options
func (_m *MockDatabase) TransactionJS(ctx context.Context, options arangodb.TransactionJSOptions) (interface{}, error) {
	ret := _m.Called(ctx, options)

	if len(ret) == 0 {
		panic("no return value specified for TransactionJS")
	}

	var r0 interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, arangodb.TransactionJSOptions) (interface{}, error)); ok {
		return rf(ctx, options)
	}
	if rf, ok := ret.Get(0).(func(context.Context, arangodb.TransactionJSOptions) interface{}); ok {
		r0 = rf(ctx, options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, arangodb.TransactionJSOptions) error); ok {
		r1 = rf(ctx, options)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDatabase_TransactionJS_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TransactionJS'
type MockDatabase_TransactionJS_Call struct {
	*mock.Call
}

// TransactionJS is a helper method to define mock.On call
//   - ctx context.Context
//   - options arangodb.TransactionJSOptions
func (_e *MockDatabase_Expecter) TransactionJS(ctx interface{}, options interface{}) *MockDatabase_TransactionJS_Call {
	return &MockDatabase_TransactionJS_Call{Call: _e.mock.On("TransactionJS", ctx, options)}
}

func (_c *MockDatabase_TransactionJS_Call) Run(run func(ctx context.Context, options arangodb.TransactionJSOptions)) *MockDatabase_TransactionJS_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(arangodb.TransactionJSOptions))
	})
	return _c
}

func (_c *MockDatabase_TransactionJS_Call) Return(_a0 interface{}, _a1 error) *MockDatabase_TransactionJS_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDatabase_TransactionJS_Call) RunAndReturn(run func(context.Context, arangodb.TransactionJSOptions) (interface{}, error)) *MockDatabase_TransactionJS_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateQueryProperties provides a mock function with given fields: ctx, options
func (_m *MockDatabase) UpdateQueryProperties(ctx context.Context, options arangodb.QueryProperties) (arangodb.QueryProperties, error) {
	ret := _m.Called(ctx, options)

	if len(ret) == 0 {
		panic("no return value specified for UpdateQueryProperties")
	}

	var r0 arangodb.QueryProperties
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, arangodb.QueryProperties) (arangodb.QueryProperties, error)); ok {
		return rf(ctx, options)
	}
	if rf, ok := ret.Get(0).(func(context.Context, arangodb.QueryProperties) arangodb.QueryProperties); ok {
		r0 = rf(ctx, options)
	} else {
		r0 = ret.Get(0).(arangodb.QueryProperties)
	}

	if rf, ok := ret.Get(1).(func(context.Context, arangodb.QueryProperties) error); ok {
		r1 = rf(ctx, options)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDatabase_UpdateQueryProperties_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateQueryProperties'
type MockDatabase_UpdateQueryProperties_Call struct {
	*mock.Call
}

// UpdateQueryProperties is a helper method to define mock.On call
//   - ctx context.Context
//   - options arangodb.QueryProperties
func (_e *MockDatabase_Expecter) UpdateQueryProperties(ctx interface{}, options interface{}) *MockDatabase_UpdateQueryProperties_Call {
	return &MockDatabase_UpdateQueryProperties_Call{Call: _e.mock.On("UpdateQueryProperties", ctx, options)}
}

func (_c *MockDatabase_UpdateQueryProperties_Call) Run(run func(ctx context.Context, options arangodb.QueryProperties)) *MockDatabase_UpdateQueryProperties_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(arangodb.QueryProperties))
	})
	return _c
}

func (_c *MockDatabase_UpdateQueryProperties_Call) Return(_a0 arangodb.QueryProperties, _a1 error) *MockDatabase_UpdateQueryProperties_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDatabase_UpdateQueryProperties_Call) RunAndReturn(run func(context.Context, arangodb.QueryProperties) (arangodb.QueryProperties, error)) *MockDatabase_UpdateQueryProperties_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateQuery provides a mock function with given fields: ctx, query
func (_m *MockDatabase) ValidateQuery(ctx context.Context, query string) error {
	ret := _m.Called(ctx, query)

	if len(ret) == 0 {
		panic("no return value specified for ValidateQuery")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, query)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockDatabase_ValidateQuery_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateQuery'
type MockDatabase_ValidateQuery_Call struct {
	*mock.Call
}

// ValidateQuery is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
func (_e *MockDatabase_Expecter) ValidateQuery(ctx interface{}, query interface{}) *MockDatabase_ValidateQuery_Call {
	return &MockDatabase_ValidateQuery_Call{Call: _e.mock.On("ValidateQuery", ctx, query)}
}

func (_c *MockDatabase_ValidateQuery_Call) Run(run func(ctx context.Context, query string)) *MockDatabase_ValidateQuery_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockDatabase_ValidateQuery_Call) Return(_a0 error) *MockDatabase_ValidateQuery_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDatabase_ValidateQuery_Call) RunAndReturn(run func(context.Context, string) error) *MockDatabase_ValidateQuery_Call {
	_c.Call.Return(run)
	return _c
}

// View provides a mock function with given fields: ctx, name
func (_m *MockDatabase) View(ctx context.Context, name string) (arangodb.View, error) {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for View")
	}

	var r0 arangodb.View
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (arangodb.View, error)); ok {
		return rf(ctx, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) arangodb.View); ok {
		r0 = rf(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(arangodb.View)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDatabase_View_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'View'
type MockDatabase_View_Call struct {
	*mock.Call
}

// View is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockDatabase_Expecter) View(ctx interface{}, name interface{}) *MockDatabase_View_Call {
	return &MockDatabase_View_Call{Call: _e.mock.On("View", ctx, name)}
}

func (_c *MockDatabase_View_Call) Run(run func(ctx context.Context, name string)) *MockDatabase_View_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockDatabase_View_Call) Return(_a0 arangodb.View, _a1 error) *MockDatabase_View_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDatabase_View_Call) RunAndReturn(run func(context.Context, string) (arangodb.View, error)) *MockDatabase_View_Call {
	_c.Call.Return(run)
	return _c
}

// ViewExists provides a mock function with given fields: ctx, name
func (_m *MockDatabase) ViewExists(ctx context.Context, name string) (bool, error) {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for ViewExists")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(ctx, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, name)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDatabase_ViewExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ViewExists'
type MockDatabase_ViewExists_Call struct {
	*mock.Call
}

// ViewExists is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockDatabase_Expecter) ViewExists(ctx interface{}, name interface{}) *MockDatabase_ViewExists_Call {
	return &MockDatabase_ViewExists_Call{Call: _e.mock.On("ViewExists", ctx, name)}
}

func (_c *MockDatabase_ViewExists_Call) Run(run func(ctx context.Context, name string)) *MockDatabase_ViewExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockDatabase_ViewExists_Call) Return(_a0 bool, _a1 error) *MockDatabase_ViewExists_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDatabase_ViewExists_Call) RunAndReturn(run func(context.Context, string) (bool, error)) *MockDatabase_ViewExists_Call {
	_c.Call.Return(run)
	return _c
}

// Views provides a mock function with given fields: ctx
func (_m *MockDatabase) Views(ctx context.Context) (arangodb.ViewsResponseReader, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Views")
	}

	var r0 arangodb.ViewsResponseReader
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (arangodb.ViewsResponseReader, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) arangodb.ViewsResponseReader); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(arangodb.ViewsResponseReader)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDatabase_Views_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Views'
type MockDatabase_Views_Call struct {
	*mock.Call
}

// Views is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockDatabase_Expecter) Views(ctx interface{}) *MockDatabase_Views_Call {
	return &MockDatabase_Views_Call{Call: _e.mock.On("Views", ctx)}
}

func (_c *MockDatabase_Views_Call) Run(run func(ctx context.Context)) *MockDatabase_Views_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockDatabase_Views_Call) Return(_a0 arangodb.ViewsResponseReader, _a1 error) *MockDatabase_Views_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDatabase_Views_Call) RunAndReturn(run func(context.Context) (arangodb.ViewsResponseReader, error)) *MockDatabase_Views_Call {
	_c.Call.Return(run)
	return _c
}

// ViewsAll provides a mock function with given fields: ctx
func (_m *MockDatabase) ViewsAll(ctx context.Context) ([]arangodb.View, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ViewsAll")
	}

	var r0 []arangodb.View
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]arangodb.View, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []arangodb.View); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]arangodb.View)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDatabase_ViewsAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ViewsAll'
type MockDatabase_ViewsAll_Call struct {
	*mock.Call
}

// ViewsAll is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockDatabase_Expecter) ViewsAll(ctx interface{}) *MockDatabase_ViewsAll_Call {
	return &MockDatabase_ViewsAll_Call{Call: _e.mock.On("ViewsAll", ctx)}
}

func (_c *MockDatabase_ViewsAll_Call) Run(run func(ctx context.Context)) *MockDatabase_ViewsAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockDatabase_ViewsAll_Call) Return(_a0 []arangodb.View, _a1 error) *MockDatabase_ViewsAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDatabase_ViewsAll_Call) RunAndReturn(run func(context.Context) ([]arangodb.View, error)) *MockDatabase_ViewsAll_Call {
	_c.Call.Return(run)
	return _c
}

// WithTransaction provides a mock function with given fields: ctx, cols, opts, commitOptions, abortOptions, w
func (_m *MockDatabase) WithTransaction(ctx context.Context, cols arangodb.TransactionCollections, opts *arangodb.BeginTransactionOptions, commitOptions *arangodb.CommitTransactionOptions, abortOptions *arangodb.AbortTransactionOptions, w arangodb.TransactionWrap) error {
	ret := _m.Called(ctx, cols, opts, commitOptions, abortOptions, w)

	if len(ret) == 0 {
		panic("no return value specified for WithTransaction")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, arangodb.TransactionCollections, *arangodb.BeginTransactionOptions, *arangodb.CommitTransactionOptions, *arangodb.AbortTransactionOptions, arangodb.TransactionWrap) error); ok {
		r0 = rf(ctx, cols, opts, commitOptions, abortOptions, w)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockDatabase_WithTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithTransaction'
type MockDatabase_WithTransaction_Call struct {
	*mock.Call
}

// WithTransaction is a helper method to define mock.On call
//   - ctx context.Context
//   - cols arangodb.TransactionCollections
//   - opts *arangodb.BeginTransactionOptions
//   - commitOptions *arangodb.CommitTransactionOptions
//   - abortOptions *arangodb.AbortTransactionOptions
//   - w arangodb.TransactionWrap
func (_e *MockDatabase_Expecter) WithTransaction(ctx interface{}, cols interface{}, opts interface{}, commitOptions interface{}, abortOptions interface{}, w interface{}) *MockDatabase_WithTransaction_Call {
	return &MockDatabase_WithTransaction_Call{Call: _e.mock.On("WithTransaction", ctx, cols, opts, commitOptions, abortOptions, w)}
}

func (_c *MockDatabase_WithTransaction_Call) Run(run func(ctx context.Context, cols arangodb.TransactionCollections, opts *arangodb.BeginTransactionOptions, commitOptions *arangodb.CommitTransactionOptions, abortOptions *arangodb.AbortTransactionOptions, w arangodb.TransactionWrap)) *MockDatabase_WithTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(arangodb.TransactionCollections), args[2].(*arangodb.BeginTransactionOptions), args[3].(*arangodb.CommitTransactionOptions), args[4].(*arangodb.AbortTransactionOptions), args[5].(arangodb.TransactionWrap))
	})
	return _c
}

func (_c *MockDatabase_WithTransaction_Call) Return(_a0 error) *MockDatabase_WithTransaction_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDatabase_WithTransaction_Call) RunAndReturn(run func(context.Context, arangodb.TransactionCollections, *arangodb.BeginTransactionOptions, *arangodb.CommitTransactionOptions, *arangodb.AbortTransactionOptions, arangodb.TransactionWrap) error) *MockDatabase_WithTransaction_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDatabase creates a new instance of MockDatabase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDatabase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDatabase {
	mock := &MockDatabase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
